feat: Added max requests parameter to jobs
psyko-gh/overcrawlrr pull request #38
Opened 2024-12-17 20:18 UTC by jordanemedlock

Added a `maxRequests` setting to both the `discover` and `smartRecommendations` jobs to limit the number of requests made during those jobs.

2024-12-20 22:53 UTC, psyko-gh requested changes
Thanks for the PR 😃 . Could you please consider my comments ?

2024-12-20 22:53 UTC, psyko-gh commented on src/service/index.ts
> +                    break;
I'd recommend adding a log statement
```suggestion
                    logger.info(`Maximum requests limit (${maxRequests}) reached. Stopping analyze here...`);
                    break;
```

2024-12-20 22:53 UTC, psyko-gh commented on src/service/index.ts
> +
This log statement should be moved at the beginning of the `processMovieResult` function, so it's also logged when running the smartRecommendation job.

2024-12-20 22:55 UTC, psyko-gh commented on src/service/index.ts
> +    var numAdded = 0;
`var`should be replaced by `let`

2024-12-20 23:09 UTC, jordanemedlock commented
Thank you for the feedback! Updated all requests :-)

2024-12-21 10:16 UTC, psyko-gh commented
Format check is failing. Can you run the `npm run format:fix` command please ?

2024-12-22 08:18 UTC, merged